'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Share2, X, Copy, Check, Download, Mail } from 'lucide-react'
import { bg, surf, bdr, ink, muted, blue, green } from '../constants/colors'
import { ARTIFACT_META } from '../constants/artifact-meta'
import { artifactToText } from '../utils'
import type { ArtifactData } from '../../types/agent.types'

export function ShareModal({
  artifact,
  onClose,
}: {
  artifact: ArtifactData;
  onClose: () => void;
}) {
  const [copied,   setCopied]   = useState(false);
  const [copiedMd, setCopiedMd] = useState(false);
  const meta    = ARTIFACT_META[artifact.type];
  const text    = artifactToText(artifact);

  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(text);
    setCopiedMd(true);
    setTimeout(() => setCopiedMd(false), 2000);
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`[Review] ${artifact.title}`);
    const body    = encodeURIComponent(`Hi,\n\nI'd love your feedback on this deliverable I built with Edge Alpha.\n\n---\n\n${text.slice(0, 1500)}${text.length > 1500 ? "\n…(truncated)" : ""}\n\n---\n\nLet me know what you think!`);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handlePDF = () => {
    const htmlLines = text.split("\n").map(line => {
      if (line.startsWith("# ")) return `<h1>${line.slice(2)}</h1>`;
      if (line.startsWith("## ")) return `<h2>${line.slice(3)}</h2>`;
      if (line.startsWith("### ")) return `<h3>${line.slice(4)}</h3>`;
      if (line.trim() === "") return "<br/>";
      if (line.startsWith("  ")) return `<p class="indent">${line.trim()}</p>`;
      return `<p>${line}</p>`;
    });
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
      <title>${artifact.title}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #18160f; max-width: 720px; margin: 40px auto; padding: 0 24px; line-height: 1.6; }
        h1 { font-size: 24px; font-weight: 600; margin: 0 0 8px; border-bottom: 2px solid #e2ddd5; padding-bottom: 12px; }
        h2 { font-size: 16px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #8a867c; margin: 20px 0 6px; }
        h3 { font-size: 14px; font-weight: 600; margin: 14px 0 4px; }
        p { font-size: 13px; margin: 3px 0; color: #18160f; }
        p.indent { padding-left: 16px; color: #5a5850; }
        br { margin: 8px 0; display: block; }
        .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2ddd5; font-size: 11px; color: #8a867c; }
        @media print { body { margin: 0; padding: 20px; } }
      </style>
    </head><body>
      ${htmlLines.join("\n")}
      <div class="footer">Generated by Edge Alpha · ${new Date().toLocaleDateString()}</div>
    </body></html>`;
    const win = window.open("", "_blank");
    if (win) {
      win.document.write(html);
      win.document.close();
      setTimeout(() => win.print(), 250);
    }
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        style={{
          position: "fixed", inset: 0, zIndex: 300,
          background: "rgba(24,22,15,0.55)",
          display: "flex", alignItems: "center", justifyContent: "center",
          padding: 24,
        }}
        onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
      >
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          transition={{ duration: 0.18 }}
          style={{
            background: bg, borderRadius: 16, width: "100%", maxWidth: 520,
            boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
            overflow: "hidden",
          }}
        >
          {/* header */}
          <div style={{ padding: "20px 24px 16px", borderBottom: `1px solid ${bdr}`, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <Share2 size={15} style={{ color: blue }} />
              <span style={{ fontSize: 14, fontWeight: 700, color: ink }}>Share with co-founder</span>
            </div>
            <button onClick={onClose} style={{ background: "none", border: "none", cursor: "pointer", color: muted, padding: 4 }}>
              <X size={16} />
            </button>
          </div>

          {/* artifact info */}
          <div style={{ padding: "16px 24px 0" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 14 }}>
              {meta && <meta.icon size={13} style={{ color: meta.color }} />}
              <span style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.12em", color: meta?.color ?? blue }}>
                {meta?.label ?? artifact.type}
              </span>
            </div>
            <p style={{ fontSize: 15, fontWeight: 600, color: ink, marginBottom: 16 }}>{artifact.title}</p>
          </div>

          {/* preview */}
          <div style={{ margin: "0 24px", borderRadius: 10, background: surf, border: `1px solid ${bdr}`, overflow: "hidden", maxHeight: 180 }}>
            <div style={{ overflowY: "auto", maxHeight: 180 }}>
              <pre style={{ margin: 0, padding: "14px 16px", fontSize: 11, color: muted, whiteSpace: "pre-wrap", lineHeight: 1.5, fontFamily: "inherit" }}>
                {text.slice(0, 600)}{text.length > 600 ? "\n…" : ""}
              </pre>
            </div>
          </div>

          {/* actions */}
          <div style={{ padding: "16px 24px 20px", display: "flex", flexDirection: "column", gap: 8 }}>
            <div style={{ display: "flex", gap: 8 }}>
              <button
                onClick={handleCopy}
                style={{
                  flex: 1, padding: "10px 14px", borderRadius: 8, fontSize: 13, fontWeight: 600,
                  background: copied ? "#F0FDF4" : surf,
                  color: copied ? green : ink,
                  border: `1px solid ${copied ? "#86EFAC" : bdr}`,
                  cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                  transition: "background .15s, color .15s",
                  fontFamily: "inherit",
                }}
              >
                {copied ? <Check size={13} /> : <Copy size={13} />}
                {copied ? "Copied!" : "Copy text"}
              </button>
              <button
                onClick={handlePDF}
                style={{
                  flex: 1, padding: "10px 14px", borderRadius: 8, fontSize: 13, fontWeight: 600,
                  background: surf, color: ink,
                  border: `1px solid ${bdr}`,
                  cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                  fontFamily: "inherit",
                }}
              >
                <Download size={13} />
                Export PDF
              </button>
            </div>
            <button
              onClick={handleCopyMarkdown}
              style={{
                width: "100%", padding: "10px 14px", borderRadius: 8, fontSize: 13, fontWeight: 600,
                background: copiedMd ? "#F5F3FF" : surf,
                color: copiedMd ? "#7C3AED" : ink,
                border: `1px solid ${copiedMd ? "#C4B5FD" : bdr}`,
                cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                transition: "background .15s, color .15s",
                fontFamily: "inherit",
              }}
            >
              {copiedMd ? <Check size={13} /> : <Copy size={13} />}
              {copiedMd ? "Copied as Markdown!" : "Copy Markdown — paste into Notion / Obsidian"}
            </button>
            <button
              onClick={handleEmail}
              style={{
                width: "100%", padding: "10px 14px", borderRadius: 8, fontSize: 13, fontWeight: 600,
                background: blue, color: "#fff",
                border: "none", cursor: "pointer",
                display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                fontFamily: "inherit",
              }}
            >
              <Mail size={13} />
              Email co-founder
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
