/** Centralized deliverable label map for sidebar display. Icons are omitted (sidebar uses its own display). */
export const AGENT_DELIVERABLES: Record<string, { type: string; label: string; prereqs?: string[] }[]> = {
  patel: [
    { type: 'icp_document',          label: 'D1 · ICP Definition' },
    { type: 'pains_gains_triggers',  label: 'D2 · Pains & Gains',       prereqs: ['icp_document'] },
    { type: 'buyer_journey',         label: 'D3 · Buyer Journey',        prereqs: ['icp_document', 'pains_gains_triggers'] },
    { type: 'positioning_messaging', label: 'D4 · Positioning',          prereqs: ['icp_document', 'pains_gains_triggers', 'buyer_journey'] },
    { type: 'outreach_sequence',     label: 'Outreach Sequence' },
    { type: 'battle_card',           label: 'Battle Card' },
    { type: 'gtm_playbook',          label: 'GTM Playbook' },
    { type: 'lead_list',             label: 'Lead List' },
    { type: 'campaign_report',       label: 'Campaign Report' },
  ],
  felix: [
    { type: 'financial_summary',     label: 'Financial Summary' },
    { type: 'financial_model',       label: 'Financial Model' },
    { type: 'investor_update',       label: 'Investor Update' },
    { type: 'board_deck',            label: 'Board Deck' },
    { type: 'cap_table_summary',     label: 'Cap Table' },
    { type: 'fundraising_narrative', label: 'Fundraising Narrative' },
  ],
  susi: [
    { type: 'sales_script',      label: 'Sales Script' },
    { type: 'call_playbook',     label: 'Call Playbook' },
    { type: 'pipeline_report',   label: 'Pipeline Report' },
    { type: 'proposal',          label: 'Proposal' },
    { type: 'win_loss_analysis', label: 'Win/Loss Analysis' },
  ],
  maya: [
    { type: 'brand_messaging',     label: 'Brand Messaging' },
    { type: 'content_calendar',    label: 'Content Calendar' },
    { type: 'seo_audit',           label: 'SEO Audit' },
    { type: 'press_kit',           label: 'Press Kit' },
    { type: 'newsletter_issue',    label: 'Newsletter Issue' },
    { type: 'brand_health_report', label: 'Brand Health Report' },
  ],
  harper: [
    { type: 'hiring_plan',         label: 'Hiring Plan' },
    { type: 'job_description',     label: 'Job Description' },
    { type: 'interview_scorecard', label: 'Interview Scorecard' },
    { type: 'offer_letter',        label: 'Offer Letter' },
    { type: 'onboarding_plan',     label: 'Onboarding Plan' },
    { type: 'comp_benchmark',      label: 'Comp Benchmark' },
  ],
  nova: [
    { type: 'pmf_survey',       label: 'PMF Survey' },
    { type: 'product_insight',  label: 'Product Insight' },
    { type: 'experiment_design',label: 'Experiment Design' },
    { type: 'roadmap',          label: 'Roadmap' },
    { type: 'user_persona',     label: 'User Persona' },
  ],
  atlas: [
    { type: 'competitive_matrix',  label: 'Competitive Matrix' },
    { type: 'battle_card',         label: 'Battle Card' },
    { type: 'market_map',          label: 'Market Map' },
    { type: 'competitor_weekly',   label: 'Weekly Intel' },
    { type: 'review_intelligence', label: 'Review Intelligence' },
  ],
  sage: [
    { type: 'strategic_plan',            label: 'Strategic Plan' },
    { type: 'investor_readiness_report', label: 'Investor Readiness' },
    { type: 'contradiction_report',      label: 'Contradiction Report' },
    { type: 'okr_health_report',         label: 'OKR Health Report' },
    { type: 'crisis_playbook',           label: 'Crisis Playbook' },
  ],
  carter: [
    { type: 'customer_health_report', label: 'Health Report' },
    { type: 'churn_analysis',         label: 'Churn Analysis' },
    { type: 'qbr_deck',               label: 'QBR Deck' },
    { type: 'expansion_playbook',     label: 'Expansion Playbook' },
    { type: 'cs_playbook',            label: 'CS Playbook' },
  ],
  riley: [
    { type: 'growth_model',       label: 'Growth Model' },
    { type: 'paid_campaign',      label: 'Ad Campaign' },
    { type: 'referral_program',   label: 'Referral Program' },
    { type: 'launch_playbook',    label: 'Launch Playbook' },
    { type: 'growth_report',      label: 'Growth Report' },
    { type: 'experiment_results', label: 'Experiment Results' },
  ],
  leo: [
    { type: 'legal_checklist',      label: 'Legal Checklist' },
    { type: 'nda',                  label: 'NDA' },
    { type: 'safe_note',            label: 'SAFE Note' },
    { type: 'contractor_agreement', label: 'Contractor Agreement' },
    { type: 'privacy_policy',       label: 'Privacy Policy' },
    { type: 'term_sheet_redline',   label: 'Term Sheet Redline' },
  ],
}

export const AGENT_META: Record<string, { name: string; role: string; emoji: string; color: string }> = {
  patel:  { name: 'Patel',  role: 'CMO · Go-to-Market',      emoji: '📈', color: '#2563EB' },
  felix:  { name: 'Felix',  role: 'CFO · Finance',            emoji: '💰', color: '#16A34A' },
  susi:   { name: 'Susi',   role: 'CRO · Sales',              emoji: '🤝', color: '#7C3AED' },
  maya:   { name: 'Maya',   role: 'CMO · Brand & Content',    emoji: '✨', color: '#DB2777' },
  harper: { name: 'Harper', role: 'CPO · People & Hiring',    emoji: '👥', color: '#EA580C' },
  nova:   { name: 'Nova',   role: 'CPO · Product',            emoji: '🚀', color: '#0891B2' },
  atlas:  { name: 'Atlas',  role: 'CSO · Competitive Intel',  emoji: '🗺️', color: '#65A30D' },
  sage:   { name: 'Sage',   role: 'CSO · Strategy',           emoji: '🧠', color: '#7C3AED' },
  carter: { name: 'Carter', role: 'CCO · Customer Success',   emoji: '❤️', color: '#DC2626' },
  riley:  { name: 'Riley',  role: 'CGO · Growth',             emoji: '📊', color: '#D97706' },
  leo:    { name: 'Leo',    role: 'CLO · Legal',               emoji: '⚖️', color: '#475569' },
}
