/**
 * Maps each artifact type to the Q-Score parameters (P1-P6) it provides evidence for.
 * Used for parameter-specific cache invalidation after artifact embedding.
 *
 * P1=Market Readiness, P2=Market Potential, P3=IP & Defensibility,
 * P4=Founder & Team, P5=Structural Impact, P6=Financials
 */

import { ARTIFACT_TYPES, type ArtifactType } from './artifact-types';
import { PARAMS, type Param } from './dimensions';

export const ARTIFACT_DIMENSION_MAP: Record<ArtifactType, Param[]> = {
  // Existing
  [ARTIFACT_TYPES.ICP_DOCUMENT]:            [PARAMS.P1, PARAMS.P2],
  [ARTIFACT_TYPES.OUTREACH_SEQUENCE]:       [PARAMS.P1],
  [ARTIFACT_TYPES.BATTLE_CARD]:             [PARAMS.P1, PARAMS.P2],
  [ARTIFACT_TYPES.GTM_PLAYBOOK]:            [PARAMS.P1, PARAMS.P2],
  [ARTIFACT_TYPES.SALES_SCRIPT]:            [PARAMS.P1],
  [ARTIFACT_TYPES.BRAND_MESSAGING]:         [PARAMS.P2],
  [ARTIFACT_TYPES.FINANCIAL_SUMMARY]:       [PARAMS.P6],
  [ARTIFACT_TYPES.LEGAL_CHECKLIST]:         [PARAMS.P3],
  [ARTIFACT_TYPES.HIRING_PLAN]:             [PARAMS.P4],
  [ARTIFACT_TYPES.PMF_SURVEY]:              [PARAMS.P1],
  [ARTIFACT_TYPES.INTERVIEW_NOTES]:         [PARAMS.P1],
  [ARTIFACT_TYPES.COMPETITIVE_MATRIX]:      [PARAMS.P2],
  [ARTIFACT_TYPES.STRATEGIC_PLAN]:          [PARAMS.P2, PARAMS.P5],
  [ARTIFACT_TYPES.PAINS_GAINS_TRIGGERS]:    [PARAMS.P1, PARAMS.P2],
  [ARTIFACT_TYPES.BUYER_JOURNEY]:           [PARAMS.P1],
  [ARTIFACT_TYPES.POSITIONING_MESSAGING]:   [PARAMS.P1, PARAMS.P2],

  // Patel
  [ARTIFACT_TYPES.LEAD_LIST]:               [PARAMS.P1, PARAMS.P2],
  [ARTIFACT_TYPES.CAMPAIGN_REPORT]:         [PARAMS.P1, PARAMS.P2],
  [ARTIFACT_TYPES.AB_TEST_RESULT]:          [PARAMS.P1],

  // Susi
  [ARTIFACT_TYPES.CALL_PLAYBOOK]:           [PARAMS.P1],
  [ARTIFACT_TYPES.PIPELINE_REPORT]:         [PARAMS.P1],
  [ARTIFACT_TYPES.PROPOSAL]:                [PARAMS.P1],
  [ARTIFACT_TYPES.WIN_LOSS_ANALYSIS]:       [PARAMS.P1, PARAMS.P2],

  // Maya
  [ARTIFACT_TYPES.CONTENT_CALENDAR]:        [PARAMS.P2],
  [ARTIFACT_TYPES.SEO_AUDIT]:               [PARAMS.P2],
  [ARTIFACT_TYPES.PRESS_KIT]:               [PARAMS.P2],
  [ARTIFACT_TYPES.NEWSLETTER_ISSUE]:        [PARAMS.P2],
  [ARTIFACT_TYPES.BRAND_HEALTH_REPORT]:     [PARAMS.P2],

  // Felix
  [ARTIFACT_TYPES.FINANCIAL_MODEL]:         [PARAMS.P6],
  [ARTIFACT_TYPES.INVESTOR_UPDATE]:         [PARAMS.P6],
  [ARTIFACT_TYPES.BOARD_DECK]:              [PARAMS.P6],
  [ARTIFACT_TYPES.CAP_TABLE_SUMMARY]:       [PARAMS.P6],
  [ARTIFACT_TYPES.FUNDRAISING_NARRATIVE]:   [PARAMS.P6],

  // Leo
  [ARTIFACT_TYPES.NDA]:                     [PARAMS.P3],
  [ARTIFACT_TYPES.SAFE_NOTE]:               [PARAMS.P6],
  [ARTIFACT_TYPES.CONTRACTOR_AGREEMENT]:    [PARAMS.P4],
  [ARTIFACT_TYPES.PRIVACY_POLICY]:          [PARAMS.P3],
  [ARTIFACT_TYPES.IP_AUDIT_REPORT]:         [PARAMS.P3],
  [ARTIFACT_TYPES.TERM_SHEET_REDLINE]:      [PARAMS.P6],

  // Harper
  [ARTIFACT_TYPES.JOB_DESCRIPTION]:         [PARAMS.P4],
  [ARTIFACT_TYPES.INTERVIEW_SCORECARD]:     [PARAMS.P4],
  [ARTIFACT_TYPES.OFFER_LETTER]:            [PARAMS.P4],
  [ARTIFACT_TYPES.ONBOARDING_PLAN]:         [PARAMS.P4],
  [ARTIFACT_TYPES.COMP_BENCHMARK]:          [PARAMS.P4],

  // Nova
  [ARTIFACT_TYPES.RETENTION_REPORT]:        [PARAMS.P1],
  [ARTIFACT_TYPES.PRODUCT_INSIGHT]:         [PARAMS.P1],
  [ARTIFACT_TYPES.EXPERIMENT_DESIGN]:       [PARAMS.P1],
  [ARTIFACT_TYPES.ROADMAP]:                 [PARAMS.P5],
  [ARTIFACT_TYPES.USER_PERSONA]:            [PARAMS.P1, PARAMS.P2],

  // Atlas
  [ARTIFACT_TYPES.COMPETITOR_WEEKLY]:       [PARAMS.P2],
  [ARTIFACT_TYPES.MARKET_MAP]:              [PARAMS.P2],
  [ARTIFACT_TYPES.REVIEW_INTELLIGENCE]:     [PARAMS.P2],

  // Sage
  [ARTIFACT_TYPES.INVESTOR_READINESS_REPORT]: [PARAMS.P5, PARAMS.P2],
  [ARTIFACT_TYPES.CONTRADICTION_REPORT]:    [PARAMS.P5],
  [ARTIFACT_TYPES.OKR_HEALTH_REPORT]:       [PARAMS.P5],
  [ARTIFACT_TYPES.CRISIS_PLAYBOOK]:         [PARAMS.P5],

  // Carter
  [ARTIFACT_TYPES.CUSTOMER_HEALTH_REPORT]:  [PARAMS.P1],
  [ARTIFACT_TYPES.CHURN_ANALYSIS]:          [PARAMS.P1],
  [ARTIFACT_TYPES.QBR_DECK]:               [PARAMS.P1],
  [ARTIFACT_TYPES.EXPANSION_PLAYBOOK]:      [PARAMS.P1, PARAMS.P6],
  [ARTIFACT_TYPES.CS_PLAYBOOK]:             [PARAMS.P1],

  // Riley
  [ARTIFACT_TYPES.GROWTH_MODEL]:            [PARAMS.P2],
  [ARTIFACT_TYPES.PAID_CAMPAIGN]:           [PARAMS.P2],
  [ARTIFACT_TYPES.REFERRAL_PROGRAM]:        [PARAMS.P1, PARAMS.P2],
  [ARTIFACT_TYPES.LAUNCH_PLAYBOOK]:         [PARAMS.P1],
  [ARTIFACT_TYPES.GROWTH_REPORT]:           [PARAMS.P1, PARAMS.P2],
  [ARTIFACT_TYPES.EXPERIMENT_RESULTS]:      [PARAMS.P1],
};
