/**
 * Maps each artifact type to the Q-Score dimensions it provides evidence for.
 * Used for dimension-specific cache invalidation after artifact embedding.
 */

import { ARTIFACT_TYPES, type ArtifactType } from './artifact-types';
import { DIMENSIONS, type Dimension } from './dimensions';

export const ARTIFACT_DIMENSION_MAP: Record<ArtifactType, Dimension[]> = {
  // Existing
  [ARTIFACT_TYPES.ICP_DOCUMENT]:            [DIMENSIONS.GTM, DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.OUTREACH_SEQUENCE]:       [DIMENSIONS.GTM],
  [ARTIFACT_TYPES.BATTLE_CARD]:             [DIMENSIONS.GTM, DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.GTM_PLAYBOOK]:            [DIMENSIONS.GTM, DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.SALES_SCRIPT]:            [DIMENSIONS.GTM, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.BRAND_MESSAGING]:         [DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.FINANCIAL_SUMMARY]:       [DIMENSIONS.FINANCIAL, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.LEGAL_CHECKLIST]:         [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.HIRING_PLAN]:             [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.PMF_SURVEY]:              [DIMENSIONS.PRODUCT, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.INTERVIEW_NOTES]:         [DIMENSIONS.PRODUCT],
  [ARTIFACT_TYPES.COMPETITIVE_MATRIX]:      [DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.STRATEGIC_PLAN]:          [DIMENSIONS.MARKET, DIMENSIONS.GTM],

  // Patel
  [ARTIFACT_TYPES.LEAD_LIST]:               [DIMENSIONS.GTM, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.CAMPAIGN_REPORT]:         [DIMENSIONS.GTM, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.AB_TEST_RESULT]:          [DIMENSIONS.GTM],

  // Susi
  [ARTIFACT_TYPES.CALL_PLAYBOOK]:           [DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.PIPELINE_REPORT]:         [DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.PROPOSAL]:                [DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.WIN_LOSS_ANALYSIS]:       [DIMENSIONS.TRACTION, DIMENSIONS.MARKET],

  // Maya
  [ARTIFACT_TYPES.CONTENT_CALENDAR]:        [DIMENSIONS.GTM],
  [ARTIFACT_TYPES.SEO_AUDIT]:               [DIMENSIONS.GTM, DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.PRESS_KIT]:               [DIMENSIONS.GTM],
  [ARTIFACT_TYPES.NEWSLETTER_ISSUE]:        [DIMENSIONS.GTM],
  [ARTIFACT_TYPES.BRAND_HEALTH_REPORT]:     [DIMENSIONS.MARKET],

  // Felix
  [ARTIFACT_TYPES.FINANCIAL_MODEL]:         [DIMENSIONS.FINANCIAL],
  [ARTIFACT_TYPES.INVESTOR_UPDATE]:         [DIMENSIONS.FINANCIAL],
  [ARTIFACT_TYPES.BOARD_DECK]:              [DIMENSIONS.FINANCIAL],
  [ARTIFACT_TYPES.CAP_TABLE_SUMMARY]:       [DIMENSIONS.FINANCIAL],
  [ARTIFACT_TYPES.FUNDRAISING_NARRATIVE]:   [DIMENSIONS.FINANCIAL],

  // Leo
  [ARTIFACT_TYPES.NDA]:                     [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.SAFE_NOTE]:               [DIMENSIONS.FINANCIAL],
  [ARTIFACT_TYPES.CONTRACTOR_AGREEMENT]:    [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.PRIVACY_POLICY]:          [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.IP_AUDIT_REPORT]:         [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.TERM_SHEET_REDLINE]:      [DIMENSIONS.FINANCIAL],

  // Harper
  [ARTIFACT_TYPES.JOB_DESCRIPTION]:         [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.INTERVIEW_SCORECARD]:     [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.OFFER_LETTER]:            [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.ONBOARDING_PLAN]:         [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.COMP_BENCHMARK]:          [DIMENSIONS.TEAM],

  // Nova
  [ARTIFACT_TYPES.RETENTION_REPORT]:        [DIMENSIONS.PRODUCT, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.PRODUCT_INSIGHT]:         [DIMENSIONS.PRODUCT],
  [ARTIFACT_TYPES.EXPERIMENT_DESIGN]:       [DIMENSIONS.PRODUCT],
  [ARTIFACT_TYPES.ROADMAP]:                 [DIMENSIONS.PRODUCT],
  [ARTIFACT_TYPES.USER_PERSONA]:            [DIMENSIONS.PRODUCT, DIMENSIONS.MARKET],

  // Atlas
  [ARTIFACT_TYPES.COMPETITOR_WEEKLY]:       [DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.MARKET_MAP]:              [DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.REVIEW_INTELLIGENCE]:     [DIMENSIONS.MARKET],

  // Sage
  [ARTIFACT_TYPES.INVESTOR_READINESS_REPORT]: [DIMENSIONS.MARKET, DIMENSIONS.GTM],
  [ARTIFACT_TYPES.CONTRADICTION_REPORT]:    [DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.OKR_HEALTH_REPORT]:       [DIMENSIONS.GTM],
  [ARTIFACT_TYPES.CRISIS_PLAYBOOK]:         [DIMENSIONS.GTM],

  // Carter
  [ARTIFACT_TYPES.CUSTOMER_HEALTH_REPORT]:  [DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.CHURN_ANALYSIS]:          [DIMENSIONS.TRACTION, DIMENSIONS.PRODUCT],
  [ARTIFACT_TYPES.QBR_DECK]:               [DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.EXPANSION_PLAYBOOK]:      [DIMENSIONS.TRACTION, DIMENSIONS.FINANCIAL],
  [ARTIFACT_TYPES.CS_PLAYBOOK]:             [DIMENSIONS.TRACTION],

  // Riley
  [ARTIFACT_TYPES.GROWTH_MODEL]:            [DIMENSIONS.GTM, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.PAID_CAMPAIGN]:           [DIMENSIONS.GTM],
  [ARTIFACT_TYPES.REFERRAL_PROGRAM]:        [DIMENSIONS.GTM, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.LAUNCH_PLAYBOOK]:         [DIMENSIONS.GTM],
  [ARTIFACT_TYPES.GROWTH_REPORT]:           [DIMENSIONS.TRACTION, DIMENSIONS.GTM],
  [ARTIFACT_TYPES.EXPERIMENT_RESULTS]:      [DIMENSIONS.PRODUCT, DIMENSIONS.GTM],
};
