/**
 * Maps each artifact type to the Q-Score dimensions it provides evidence for.
 * Used for dimension-specific cache invalidation after artifact embedding.
 */

import { ARTIFACT_TYPES, type ArtifactType } from './artifact-types';
import { DIMENSIONS, type Dimension } from './dimensions';

export const ARTIFACT_DIMENSION_MAP: Record<ArtifactType, Dimension[]> = {
  [ARTIFACT_TYPES.ICP_DOCUMENT]:       [DIMENSIONS.GTM, DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.OUTREACH_SEQUENCE]:  [DIMENSIONS.GTM],
  [ARTIFACT_TYPES.BATTLE_CARD]:        [DIMENSIONS.GTM, DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.GTM_PLAYBOOK]:       [DIMENSIONS.GTM, DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.SALES_SCRIPT]:       [DIMENSIONS.GTM, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.BRAND_MESSAGING]:    [DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.FINANCIAL_SUMMARY]:  [DIMENSIONS.FINANCIAL, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.LEGAL_CHECKLIST]:    [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.HIRING_PLAN]:        [DIMENSIONS.TEAM],
  [ARTIFACT_TYPES.PMF_SURVEY]:         [DIMENSIONS.PRODUCT, DIMENSIONS.TRACTION],
  [ARTIFACT_TYPES.INTERVIEW_NOTES]:    [DIMENSIONS.PRODUCT],
  [ARTIFACT_TYPES.COMPETITIVE_MATRIX]: [DIMENSIONS.MARKET],
  [ARTIFACT_TYPES.STRATEGIC_PLAN]:     [DIMENSIONS.MARKET, DIMENSIONS.GTM],
};
