'use client'

/**
 * Consumes the SSE stream from /api/strategy/propose or /api/strategy/nudge — a
 * generalisation of the exact parsing loop app/founder/profile-builder/page.tsx's
 * `streamExtract` already uses (data: {...}\n\n, ending [DONE]), not an invented
 * pattern. Shared by TheRead/ProposedDirection (propose) and NudgeExchange (nudge)
 * since both endpoints emit the identical delta/done shape.
 */

import { useCallback, useRef, useState } from 'react'
import { readSSE } from '@/features/shared/lib/readSSE'

export interface StreamedProposal {
  read: string
  mission: string
  priorities: string[]
  goals: string[]
  /** Absent on a nudge response — the six-step document isn't regenerated by one. */
  document?: string
}

/** Mirrors STRATEGY_READ_DELIMITER in lib/prompts/composer/mandate.ts. */
const READ_DELIMITER = '<<<END_READ>>>'

export function useStreamedProposal() {
  const [streaming, setStreaming] = useState(false)
  const [readText, setReadText] = useState('')
  // True once the delimiter has arrived — "the read" itself is fully typed, but the
  // connection is still open, silently generating the six-step document behind it
  // (~60-90s). Without this, the UI has nothing to distinguish "still typing" from
  // "read is done, working on the rest" — both just look like a frozen cursor.
  const [readDone, setReadDone] = useState(false)
  const [proposal, setProposal] = useState<StreamedProposal | null>(null)
  const [error, setError] = useState<string | null>(null)
  const full = useRef('')

  const run = useCallback(async (endpoint: string, body: Record<string, unknown>) => {
    setStreaming(true)
    setError(null)
    setProposal(null)
    setReadText('')
    setReadDone(false)
    full.current = ''
    try {
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      if (!res.ok || !res.body) {
        const errBody = await res.json().catch(() => ({}))
        setError(errBody.error ?? `Request failed (${res.status})`)
        return
      }
      await readSSE(res.body, evt => {
        if (evt.type === 'delta') {
          full.current += evt.text as string
          // Only what's before the delimiter is "the read" — live-typing the rest
          // (the slower six-step document) would look like markdown typing itself,
          // not Morgan talking to the founder (UX_SPEC_the_frame.md §3).
          const idx = full.current.indexOf(READ_DELIMITER)
          setReadText(idx === -1 ? full.current : full.current.slice(0, idx))
          if (idx !== -1) setReadDone(true)
        } else if (evt.type === 'done') {
          if (evt.error) setError(evt.error as string)
          else if (evt.proposal) setProposal(evt.proposal as StreamedProposal)
        }
      })
    } catch {
      setError('Could not reach the server. Try again.')
    } finally {
      setStreaming(false)
    }
  }, [])

  return { streaming, readText, readDone, proposal, error, run }
}
