/**
 * LLM Semantic Matcher
 *
 * Replaces pgvector cosine similarity for Layer 2 evidence cross-reference.
 * Uses a single Groq LLM call to check whether a founder's agent artifacts
 * corroborate or conflict with their assessment claims.
 *
 * Advantages over vector embeddings:
 *  - No OPENAI_API_KEY required — uses existing GROQ_API_KEY
 *  - More accurate for numeric comparisons ("$50K MRR" vs "monthly revenue of fifty thousand")
 *  - Works from day one — no backfill of existing artifacts needed
 *  - No pgvector infra or artifact_embeddings table required
 */

import { callOpenRouter } from '@/lib/openrouter';

export interface MatchResult {
  claim: string;
  verdict: 'corroborated' | 'conflicting' | 'unverified';
  evidence: string;          // The artifact snippet that matched (or '')
  artifactType: string;      // e.g. 'financial_summary'
  dimension: string;
}

interface ArtifactSnippet {
  artifactType: string;
  text: string;
}

/**
 * Flatten a JSON artifact content object into a compact text snippet.
 * Limits to 400 chars per artifact to keep the prompt manageable.
 */
export function artifactToSnippet(content: Record<string, unknown>, artifactType: string): string {
  const parts: string[] = [`[${artifactType}]`];
  for (const [key, val] of Object.entries(content)) {
    if (val === null || val === undefined || val === '') continue;
    const str = Array.isArray(val)
      ? val.slice(0, 3).map(v => (typeof v === 'object' ? JSON.stringify(v) : String(v))).join(', ')
      : typeof val === 'object'
      ? JSON.stringify(val).slice(0, 120)
      : String(val);
    parts.push(`${key}: ${str}`);
    if (parts.join(' ').length > 380) break; // cap per artifact
  }
  return parts.join(' | ').slice(0, 420);
}

/**
 * Use an LLM to check each claim against a set of artifact snippets.
 *
 * Returns one MatchResult per claim.
 * Falls back to 'unverified' for every claim if the LLM call fails.
 */
export async function matchClaimsAgainstArtifacts(
  claims: { text: string; dimension: string; field: string }[],
  artifacts: ArtifactSnippet[]
): Promise<MatchResult[]> {
  if (claims.length === 0) return [];
  if (artifacts.length === 0) {
    return claims.map(c => ({
      claim: c.text, verdict: 'unverified', evidence: '', artifactType: '', dimension: c.dimension,
    }));
  }

  const claimsBlock = claims
    .map((c, i) => `CLAIM ${i + 1} [${c.dimension}]: ${c.text}`)
    .join('\n');

  const artifactsBlock = artifacts
    .map((a, i) => `ARTIFACT ${i + 1}: ${a.text}`)
    .join('\n');

  const prompt = `You are a startup data auditor. Compare each CLAIM from a founder's self-assessment against ARTIFACT snippets generated by the founder's AI agents.

For each claim, determine:
- "corroborated" — an artifact contains the same or consistent data (within 50% for numbers)
- "conflicting"   — an artifact contains a significantly different number (>50% deviation) or contradictory statement
- "unverified"    — no artifact mentions this data point

CLAIMS:
${claimsBlock}

ARTIFACT SNIPPETS:
${artifactsBlock}

Return ONLY a valid JSON array, one object per claim, in order:
[{"verdict":"corroborated"|"conflicting"|"unverified","evidence":"<exact snippet text that matched, or empty string>","artifactType":"<artifact type, or empty>"}]`;

  try {
    const raw = await callOpenRouter(
      [{ role: 'user', content: prompt }],
      { maxTokens: 400, temperature: 0.0 },
    );

    const clean = raw
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```$/i, '')
      .trim();

    const parsed = JSON.parse(clean) as {
      verdict: string;
      evidence: string;
      artifactType: string;
    }[];

    return claims.map((c, i) => {
      const r = parsed[i];
      const verdict = r?.verdict === 'corroborated' || r?.verdict === 'conflicting'
        ? r.verdict
        : 'unverified';
      return {
        claim:       c.text,
        verdict,
        evidence:    r?.evidence ?? '',
        artifactType: r?.artifactType ?? '',
        dimension:   c.dimension,
      };
    });
  } catch {
    // LLM call failed — return all as unverified (no penalty to founder)
    return claims.map(c => ({
      claim: c.text, verdict: 'unverified', evidence: '', artifactType: '', dimension: c.dimension,
    }));
  }
}
