-- ============================================================
-- Consolidates:
--   20260310000001_agent_messages_user_id_indexes.sql
--   20260310000002_messages_table.sql
--   20260310000003_agent_actions_type_cta.sql
-- ============================================================

-- ============================================================
-- SOURCE: 20260310000001_agent_messages_user_id_indexes.sql
-- ============================================================

-- ============================================================
-- Add user_id to agent_messages for direct user-scoped queries
-- (activity-boost message count, future analytics)
-- Also add missing performance indexes.
-- ============================================================

-- 1. Add user_id to agent_messages, back-filled via parent conversation
ALTER TABLE agent_messages
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- Back-fill from agent_conversations
UPDATE agent_messages am
SET user_id = ac.user_id
FROM agent_conversations ac
WHERE am.conversation_id = ac.id
  AND am.user_id IS NULL;

-- 2. Add sender column alias (chat route uses 'sender', schema uses 'role')
-- The activity-boost route queries .eq('sender', 'user') — create the column if missing
ALTER TABLE agent_messages
  ADD COLUMN IF NOT EXISTS sender TEXT
    GENERATED ALWAYS AS (role) STORED;

-- 3. Performance indexes
CREATE INDEX IF NOT EXISTS idx_agent_activity_user_created
  ON agent_activity(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_artifacts_user_type
  ON agent_artifacts(user_id, artifact_type);

CREATE INDEX IF NOT EXISTS idx_agent_messages_user_created
  ON agent_messages(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_qscore_history_user_calculated
  ON qscore_history(user_id, calculated_at DESC);

CREATE INDEX IF NOT EXISTS idx_outreach_sends_resend_id
  ON outreach_sends(resend_id);

CREATE INDEX IF NOT EXISTS idx_deals_user_stage
  ON deals(user_id, stage);

-- 4. RLS policy for direct user_id access on agent_messages
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'agent_messages'
      AND policyname = 'Users can view own messages by user_id'
  ) THEN
    CREATE POLICY "Users can view own messages by user_id"
      ON agent_messages FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'agent_messages'
      AND policyname = 'Users can insert messages by user_id'
  ) THEN
    CREATE POLICY "Users can insert messages by user_id"
      ON agent_messages FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- SOURCE: 20260310000002_messages_table.sql
-- ============================================================

-- Real 2-way messaging between founders and investors.
-- Messages are scoped to a connection_request (the accepted connection context).

CREATE TABLE IF NOT EXISTS messages (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  connection_request_id UUID NOT NULL REFERENCES connection_requests(id) ON DELETE CASCADE,
  sender_id            UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recipient_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  body                 TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
  read_at              TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_messages_connection ON messages(connection_request_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_messages_recipient   ON messages(recipient_id, read_at) WHERE read_at IS NULL;

-- RLS: only sender and recipient can see messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "messages_select" ON messages
  FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = recipient_id);

CREATE POLICY "messages_insert" ON messages
  FOR INSERT WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "messages_update_read" ON messages
  FOR UPDATE USING (auth.uid() = recipient_id)
  WITH CHECK (auth.uid() = recipient_id);

-- ============================================================
-- SOURCE: 20260310000003_agent_actions_type_cta.sql
-- ============================================================

-- Add action_type and cta_label to agent_actions so they persist across sessions.
-- Previously these were generated by the LLM but not stored — lost on page reload.

ALTER TABLE agent_actions
  ADD COLUMN IF NOT EXISTS action_type TEXT DEFAULT 'task',
  ADD COLUMN IF NOT EXISTS cta_label   TEXT DEFAULT 'Do it';

-- Index for filtering by action_type (e.g. "show only send_outreach actions")
CREATE INDEX IF NOT EXISTS idx_agent_actions_type
  ON agent_actions(user_id, action_type);
