-- Add action_type and cta_label to agent_actions so they persist across sessions.
-- Previously these were generated by the LLM but not stored — lost on page reload.

ALTER TABLE agent_actions
  ADD COLUMN IF NOT EXISTS action_type TEXT DEFAULT 'task',
  ADD COLUMN IF NOT EXISTS cta_label   TEXT DEFAULT 'Do it';

-- Index for filtering by action_type (e.g. "show only send_outreach actions")
CREATE INDEX IF NOT EXISTS idx_agent_actions_type
  ON agent_actions(user_id, action_type);
